name: Build, CI, and Deploy

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  repository_dispatch:
  # schedule:
  #   # https://crontab.guru/#0_7_*_*_*
  #   - cron: "0 7 * * *"

env:
  DOCKER_IMAGE: "jefftriplett/devd"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint-dockerfile:
    runs-on: [ubuntu-latest]
    container:
      image: hadolint/hadolint:latest-debian
      options: --entrypoint /bin/sh

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lints Dockerfile
        run: |
            #!/usr/bin/env sh
            set -ex
            hadolint --version
            hadolint --ignore=DL3008 --ignore=DL3009 --ignore=DL3013 --ignore=DL3025 Dockerfile

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Production Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
