name: Build, CI, and Deploy

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  repository_dispatch:
  # uncomment this for nightly builds...
  # schedule:
  #   # https://crontab.guru/#0_7_*_*_*
  #   - cron: "0 7 * * *"

jobs:
  lint-dockerfile:
    runs-on: [ubuntu-latest]
    container:
      image: hadolint/hadolint:latest-debian
      options: --entrypoint /bin/sh

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Lints Dockerfile
        run: |
            #!/usr/bin/env sh
            set -ex
            hadolint --version
            hadolint Dockerfile

  docker:
    needs: lint-dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Production Docker image
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/${{ github.repository }}:latest

  # delete-outdated-packages:
  #   needs: docker
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cleanup old packages
  #       uses: actions/delete-package-versions@v2
  #       with:
  #         min-versions-to-keep: 4
  #         package-name: devd
